# fly.toml app configuration file generated for blibber26 on 2023-12-14T19:01:31-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blibber26"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 8082
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
